---
title: "Iterative mcmc"
output: html_document
---
### Spatio - temporal outbreak detection on real data analysis

```{r}
library(rstan)
options(mc.cores = parallel::detectCores())
library(dplyr)
library(ggplot2)
library(bayesplot)
library(Matrix)
```

```{r}
## Adding the area 
# dt = read.table('pop_ma_dc.txt',sep=',',header = TRUE)[,-1]
# dim(dt)
# dim(pop_dc_MA)
# head(dt[,1:5])
# head(pop_dc_MA[,1:5])
# 
# class(dt[,-3])
# dim(dt[,-3])
# class(pop_dc_MA)
# pop_dc_MA$area = dt$area
# 
# dt_new =  cbind(pop_dc_MA[,1:2],dt$area,pop_dc_MA[,3:370])
# saveRDS(dt_new,file = paste(path_data,'\\','pop_dc_MA_temp_area.rds',sep=''))
# identical(pop_dc_MA,dt[,-3])
```

```{r}
path_data= "R:\\Research problems\\JAGS\\Spatial temporal Bayesian hierarchical model\\outbreak_detection_marginalization(Latest)\\Favorite Baby!!\\data"
pop_dc_MA=readRDS(paste(path_data,'\\','pop_dc_MA_temp_area.rds',sep=''))
W=readRDS(paste(path_data,'\\','ma_mat.rds',sep=''))
# Y_raw=as.matrix(pop_dc_MA[,3:ncol(pop_dc_MA)])
Y_raw=as.matrix(pop_dc_MA[,4:ncol(pop_dc_MA)]) ## With new variable population density
Y_date=seq(as.Date('2020-01-22'),length.out = ncol(Y_raw),by='days')
colnames(Y_raw)=format(Y_date,'%m/%d/%y')
Y_raw[,c('11/26/20','12/25/20',"01/01/21")]=round(Y_raw[,c('11/27/20','12/26/20',"01/02/21")]/2)
Y_raw[,c('11/27/20','12/26/20',"01/02/21")]=round(Y_raw[,c('11/27/20','12/26/20',"01/02/21")]/2)

newdate_s=which(colnames(Y_raw)=='06/15/20')
# newdate_e=which(colnames(Y_raw)==colnames(Y_raw)[ncol(Y_raw)]) # default
newdate_e=which(colnames(Y_raw)=="12/31/20")
(newdate_e-newdate_s)
Y=Y_raw[,newdate_s:newdate_e]

## time
T = ncol(Y);T
## Number of counties
n_region = nrow(Y);n_region
## population
Xpop = (pop_dc_MA$pop)


Y_inci=c()
denom_incident = 10^6
for(n_region_i in seq_len(n_region)){
  Y_inci_row_temp = round(Y[n_region_i,]/Xpop[n_region_i]*denom_incident)
  Y_inci = rbind(Y_inci,Y_inci_row_temp)
}

rownames(Y_inci)=pop_dc_MA$subregion
DOW = factor(weekdays(as.Date(colnames(Y),'%m/%d/%y')),levels = c("Monday","Tuesday",   "Wednesday", "Thursday",  "Friday",    "Saturday",  "Sunday"))
```

## Separate spatial error and temoral error Model preparation
```{r}
stan_code_path = "R:\\Research problems\\JAGS\\Spatial temporal Bayesian hierarchical model\\outbreak_detection_marginalization(Latest)\\Favorite Baby!!\\stan code"
stan_code_name_pool = c("CAR_with_multi_err_temp","CAR","IAR")
stan_code_name = stan_code_name_pool[3]
# toy_model = stan_model(file = paste(stan_code_path,"\\",stan_code_name,".stan",sep=''))
# saveRDS(toy_model,file=paste(path_data,'\\',stan_code_name,'.rds',sep=''))

toy_model = readRDS(paste(path_data,'\\',stan_code_name,'.rds',sep=''))
```


Tuning parameters control
```{r}
time_window = 21 # The time window for iterative fitting
n_iter = 8000
n_chains = 4
weights_for_pred = 1 # w*(pred) + (1-w)*true

## Compute the Bayesian p-value
get_p_val= function(Y,Y_pred_mat){
  p_val = c()
  for(i in 1:length(Y)){
    p_val = c(p_val, mean(Y_pred_mat[,i]>Y[i]))
  }
  return(p_val)
}

build_large_w <- function(W,t){
    colnames(W) <- NULL
    W <- as.matrix(W)
    nrows <- nrow(W)
    temp_matrix <- W
    for(i in 1:(t-1)){
        temp_matrix <- bdiag(temp_matrix,W)
    }
    temp_matrix <- as.matrix(temp_matrix)
    M <- matrix(0,t,t)
    diag(M[-nrow(M),-1]) <- 1; diag(M[-1,-nrow(M)]) <- 1
    identity <- diag(nrows)
    M <- kronecker(M,identity)
    final_matrix <- temp_matrix + M
    return(final_matrix)
}
```

```{r}
Y_original = Y ## Copy of the true count
day_last = ncol(Y)-time_window
# day_last =100 # For testing
n_region = nrow(Y)
T_window = time_window
logoffset = log(pop_dc_MA$pop)
Xtime = log(1:(T_window+1)+0.01)
Xden = log(pop_dc_MA$pop /pop_dc_MA$`dt$area`)
W_extended = build_large_w(W,time_window+1)

Y_pred_collection = array(NA,dim = c(n_iter*2,n_region,day_last))
# EY_pred_collection = array(NA,dim = c(n_iter*2,n_region,day_last))
min_n_eff_recording=c()
for(day_b in 1:day_last){
  day_e = day_b + time_window-1
  Xdow = model.matrix(~DOW[day_b:(day_e+1)])
  Y_temp=cbind(Y[,day_b:day_e])
  data0 = list(
    # T = T_window,
    # n = n_region,
    # Y = Y_temp,
    T0 = T_window,## For STAR model
    n0 = n_region,## For STAR model
    n = (T_window+1)*n_region, ## For STAT model
    Y =c(Y_temp), ## For STAR model
    Xdow = Xdow,
    Xtime = Xtime,
    Xden=Xden,
    logoffset=logoffset,
    W=W_extended,## For STAR model
    W_n = sum(W_extended)/2 ## For STAR model
  )
  samples_temp = sampling(toy_model,data=data0,chains=n_chains, iter = n_iter,control = list(adapt_delta =0.9,max_treedepth = 15,metric='diag_e'),pars = c("err_spt_uncentered"),include=FALSE)
  cat(paste("We are making prediction on day ",day_b+T_window," now!\n",sep=''))
  check_hmc_diagnostics(samples_temp)
  cat(paste("The smallest eff size of the current model is ",min(summary(samples_temp)$summary[,'n_eff']),"\n",sep=''))
  min_n_eff_recording = c(min_n_eff_recording,min(summary(samples_temp)$summary[,'n_eff']))
  pred_temp = extract(samples_temp,pars = c('Y_pred','EY_pred'))
  ## Collecting predictions
  Y_pred_collection[,,day_b]=pred_temp$Y_pred
  # EY_pred_collection[,,day_b]=pred_temp$EY_pred
  
  ## Replace next round data w*pred + (1-w)*true
  p_val_Y_binary = (get_p_val(Y_original[,day_e+1],pred_temp$Y_pred)<0.05)
  Y[,day_e+1] = round(Y[,day_e+1] * (1-p_val_Y_binary) + ((1-weights_for_pred)*Y[,day_e+1]+weights_for_pred*apply(pred_temp$Y_pred,2,median))* p_val_Y_binary)
}
saveRDS(min_n_eff_recording,file=paste(path_data,'\\min_n_eff_recording.rds',sep=''))
saveRDS(Y_pred_collection,file=paste(path_data,'\\Y_pred_collection.rds',sep=''))
```

```{r}
# pars0 = c('b_dow','b_trend','b_den',"rho_temp","rho_spat","tau_temp","tau_spat")
pars0 = c('b_dow','b_trend','b_den',"tau_spt")

print(samples_temp,pars=c(pars0,c("err_spt")))

View(summary(samples_temp)$summary)
saveRDS(toy_samples,file=paste(path_data,'\\','toy_samples.rds',sep=''))
mcmc_pairs(toy_samples,pars =  c('err_spat[1]','err_spat[2]','err_spat[3]'))
mcmc_trace(toy_samples,pars = c('err_spat[1]','err_spat[2]','err_spat[3]'))

mcmc_trace(toy_samples,regex_pars = pars0[1:5])
mcmc_pairs(toy_samples,pars = pars0)

mcmc_dens(toy_samples,regex_pars = 'Y_pred')

Y[,day_e+1]
exp(apply(extract(samples_temp,pars='EY_pred')$EY_pred,2,mean))
round((apply(extract(samples_temp,pars='Y_pred')$Y_pred,2,mean)))
round((apply(extract(samples_temp,pars='Y_pred')$Y_pred,2,sd)))
get_p_val= function(Y,Y_pred_mat){
  p_val = c()
  for(i in 1:length(Y)){
    p_val = c(p_val, mean(Y_pred_mat[,i]>Y[i]))
  }
  return(p_val)
}

mat = extract(toy_samples,pars="Y_pred",permuted=FALSE)
View(mat[,,13])
matplot(1:1500,mat[,,13],typ='l')
ess_bulk(mat[,,13])
ess_tail(mat[,,13])
Rhat(mat[,,13])
get_p_val(Y=Y[,130],Y_pred_mat =extract(toy_samples,pars='Y_pred')$Y_pred)
get_p_val(Y=Y[,130],Y_pred_mat =exp(extract(toy_samples,pars='EY_pred')$EY_pred) )
```